language: php

services: docker

php:
  - 5.6
  - 7.0

env:
  - TAG=10.1
  - TAG=pinba

before_script:
  - image="choobs/mariadb:$TAG"
  - docker build -t "$image" "$TAG"
  - docker images
  - docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=test --name db "$image"
  - docker ps -a
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - ./bin/phpunit
